// <auto-generated />
using DescDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DescDatabase.Migrations
{
    [DbContext(typeof(DescDBContext))]
    [Migration("20200722193445_FirstDESCMIgration")]
    partial class FirstDESCMIgration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DescLogicFramework.LithologicDescription", b =>
                {
                    b.Property<string>("LithologicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LithologicID");

                    b.ToTable("Descriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
