// <auto-generated />
using System;
using DescDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DescDatabase.Migrations
{
    [DbContext(typeof(DescDBContext))]
    [Migration("20200722225306_AddedSectionInfo")]
    partial class AddedSectionInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DescLogicFramework.LithologicDescription", b =>
                {
                    b.Property<string>("LithologicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionInfoSectionTextID")
                        .HasColumnType("int");

                    b.HasKey("LithologicID");

                    b.HasIndex("SectionInfoSectionTextID");

                    b.ToTable("LithologicDescriptions");
                });

            modelBuilder.Entity("DescLogicFramework.Measurement", b =>
                {
                    b.Property<int>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InstrumentReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionInfoSectionTextID")
                        .HasColumnType("int");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("SectionInfoSectionTextID");

                    b.ToTable("MeasurementDescriptions");
                });

            modelBuilder.Entity("DescLogicFramework.SectionInfo", b =>
                {
                    b.Property<int>("SectionTextID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Core")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expedition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionTextID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DescLogicFramework.LithologicDescription", b =>
                {
                    b.HasOne("DescLogicFramework.SectionInfo", "SectionInfo")
                        .WithMany()
                        .HasForeignKey("SectionInfoSectionTextID");
                });

            modelBuilder.Entity("DescLogicFramework.Measurement", b =>
                {
                    b.HasOne("DescLogicFramework.SectionInfo", "SectionInfo")
                        .WithMany()
                        .HasForeignKey("SectionInfoSectionTextID");
                });
#pragma warning restore 612, 618
        }
    }
}
