// <auto-generated />
using System;
using DescLogicFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DescLogicFramework.Migrations.LithologyDBMigrations
{
    [DbContext(typeof(LithologyDBContext))]
    [Migration("20200915185417_ChangedDescriptionValuePairValueMaxLength")]
    partial class ChangedDescriptionValuePairValueMaxLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DescLogicFramework.DescriptionColumnValuePair", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColumnName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LithologicDescriptionLithologicID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(5000)")
                        .HasMaxLength(5000);

                    b.HasKey("ID");

                    b.HasIndex("LithologicDescriptionLithologicID");

                    b.ToTable("DescriptionColumnValuePairs");
                });

            modelBuilder.Entity("DescLogicFramework.LithologicDescription", b =>
                {
                    b.Property<string>("LithologicID")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DescriptionGroup")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DescriptionReport")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DescriptionTab")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DescriptionType")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("SectionInfoID")
                        .HasColumnType("int");

                    b.HasKey("LithologicID");

                    b.HasIndex("SectionInfoID");

                    b.ToTable("LithologicDescriptions");
                });

            modelBuilder.Entity("DescLogicFramework.LithologicSubinterval", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LithologicDescriptionLithologicID")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("LithologicSubID")
                        .HasColumnType("int");

                    b.Property<int?>("SectionInfoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LithologicDescriptionLithologicID");

                    b.HasIndex("SectionInfoID");

                    b.ToTable("LithologicSubintervals");
                });

            modelBuilder.Entity("DescLogicFramework.SectionInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Core")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expedition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionTextID")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DescLogicFramework.DescriptionColumnValuePair", b =>
                {
                    b.HasOne("DescLogicFramework.LithologicDescription", null)
                        .WithMany("Data")
                        .HasForeignKey("LithologicDescriptionLithologicID");
                });

            modelBuilder.Entity("DescLogicFramework.LithologicDescription", b =>
                {
                    b.HasOne("DescLogicFramework.SectionInfo", "SectionInfo")
                        .WithMany()
                        .HasForeignKey("SectionInfoID");
                });

            modelBuilder.Entity("DescLogicFramework.LithologicSubinterval", b =>
                {
                    b.HasOne("DescLogicFramework.LithologicDescription", "LithologicDescription")
                        .WithMany("LithologicSubintervals")
                        .HasForeignKey("LithologicDescriptionLithologicID");

                    b.HasOne("DescLogicFramework.SectionInfo", "SectionInfo")
                        .WithMany()
                        .HasForeignKey("SectionInfoID");
                });
#pragma warning restore 612, 618
        }
    }
}
